### ISSUE TITLE
Integration throws error when trying to update target temperature attribute

### ISSUE THREAD

**Issue by friggeri** [explosivo22/rinnaicontrolr-ha#21]
This happens in several cases: 

1/ on its own:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 210, in state_attributes
    self.target_temperature,
  File "/config/custom_components/rinnai/water_heater.py", line 92, in target_temperature
    return self._device.target_temperature
  File "/config/custom_components/rinnai/device.py", line 91, in target_temperature
    return float(self._device_information["data"]["getDevice"]["shadow"]["set_domestic_temperature"])
TypeError: float() argument must be a string or a number, not 'NoneType'
  File "/config/custom_components/rinnai/water_heater.py", line 92, in target_temperature
    return self._device.target_temperature
  File "/config/custom_components/rinnai/device.py", line 91, in target_temperature
    return float(self._device_information["data"]["getDevice"]["shadow"]["set_domestic_temperature"])
TypeError: float() argument must be a string or a number, not 'NoneType'
```

2/ when trying to start recirculation:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 552, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 349, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 367, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 570, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/rinnai/water_heater.py", line 130, in async_start_recirculation
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 210, in state_attributes
    self.target_temperature,
  File "/config/custom_components/rinnai/water_heater.py", line 92, in target_temperature
    return self._device.target_temperature
  File "/config/custom_components/rinnai/device.py", line 91, in target_temperature
    return float(self._device_information["data"]["getDevice"]["shadow"]["set_domestic_temperature"])
TypeError: float() argument must be a string or a number, not 'NoneType'
```

When trying to stop recirculation:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 552, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 349, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 367, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 570, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/rinnai/water_heater.py", line 134, in async_stop_recirculation
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 210, in state_attributes
    self.target_temperature,
  File "/config/custom_components/rinnai/water_heater.py", line 92, in target_temperature
    return self._device.target_temperature
  File "/config/custom_components/rinnai/device.py", line 91, in target_temperature
    return float(self._device_information["data"]["getDevice"]["shadow"]["set_domestic_temperature"])
TypeError: float() argument must be a string or a number, not 'NoneType'
```

**Comment by explosivo22** [comment]
That is interesting. I will investigate on mine and from your logs and see what I can come up with.

**Comment by explosivo22** [comment]
Hey @friggeri,
I have been unable to replicate this issue on my end.

Can you give me the model of your water heater so I can do some more digging?  I am thinking it could possibly be related to this since they could all pull different information.  Model testing can be hard here since I only have one water heater to test with, but I will see what I can find out.

Could you also try the dev release and let me know if a small modification I made fixes your issue?
