### ISSUE TITLE
Cannot login to Rinnai account with latest updates to HA

### ISSUE THREAD

**Issue by psmith3** [explosivo22/rinnaicontrolr-ha#25]
Started seeing issues with an unknown error in the integration with HA. Have been running integration for months. Removed repository in HACS, reloaded and reinstalled integration and now cannot login to Rinnai account. Even update password in iOS app, but still no joy. I also update HA OS and Supervisor with no fix. Here is what I am running on HA. 

Home Assistant Core 2022.5.2

Home Assistant Supervisor 2022.05.0

Home Assistant OS 7.6

Kernel version 5.10.108

**Comment by explosivo22** [comment]
I have started to see this on 2022.5. I have been having to restart again after every update to get HA to pull in the dependencies correctly. I am sure this could be happening from a clean install from HACS as well. The issue seems to stem from botocore. I am running 2022.5.2 currently with the integration working. Could you try logging in and attaching any errors from the log? We may have to turn on debugging for the component.

**Comment by psmith3** [comment]
Yes. Here you go from just now. 

`This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/rinnai/config_flow.py:22 
Integration: Rinnai Control-R Water Heater (documentation) 
First occurred: 8:28:14 PM (1 occurrences) 
Last logged: 8:28:14 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/httpsession.py", line 178, in send
    response = await self._session.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 539, in _request
    raise ServerTimeoutError(
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host http://169.254.169.254/latest/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/rinnai/config_flow.py", line 46, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/rinnai/config_flow.py", line 22, in validate_input
    api = await async_get_api(
  File "/usr/local/lib/python3.9/site-packages/aiorinnai/api.py", line 114, in async_get_api
    await wh._get_initial_token()
  File "/usr/local/lib/python3.9/site-packages/aiorinnai/api.py", line 78, in _get_initial_token
    await self._store_token(await aws.authenticate_user())
  File "/usr/local/lib/python3.9/site-packages/aiorinnai/aws_srp.py", line 222, in authenticate_user
    async with boto_client as client:
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/session.py", line 22, in __aenter__
    self._client = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/session.py", line 102, in _create_client
    credentials = await self.get_credentials()
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/session.py", line 133, in get_credentials
    self._credentials = await (self._components.get_component(
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/credentials.py", line 814, in load_credentials
    creds = await provider.load()
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/credentials.py", line 486, in load
    metadata = await fetcher.retrieve_iam_role_credentials()
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/utils.py", line 176, in retrieve_iam_role_credentials
    token = await self._fetch_metadata_token()
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/utils.py", line 89, in _fetch_metadata_token
    response = await session.send(request.prepare())
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/httpsession.py", line 209, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"

`

**Comment by psmith3** [comment]
> I have started to see this on 2022.5. I have been having to restart again after every update to get HA to pull in the dependencies correctly. I am sure this could be happening from a clean install from HACS as well. The issue seems to stem from botocore. I am running 2022.5.2 currently with the integration working. Could you try logging in and attaching any errors from the log? We may have to turn on debugging for the component.

Yes, it was working for me in 2022.5.1 until I upgraded to 5.2 tonight and then could not get it to work again. When I uninstalled and reinstalled, I could not get passed the initial install.

**Comment by andrewradin** [comment]
I have the similar issues on upgrade of 2002.5.2. so it is not an isolated incident.

**Comment by explosivo22** [comment]
I believe this is from an underlying dependency I am looking into.  @andrewradin are you still connected and pulling information?  I have managed to just restart and mine is still pulling information, but I am checking out the dependency changes now.

**Comment by explosivo22** [comment]
Would one of you be willing to try out installing the dev version from HACS list to see if your issue is resolved?  I am hoping that updating these dependencies will fix this.  Thanks.

**Comment by andrewradin** [comment]
Here is what I see in my logfile. Warminator is the name of my control-r 
Looks to me like it is trying to connect to http://169.254.169.254/latest/api/token which is suspiciously an ec2 internal network address. See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
hopefully that is enough of a clue to debug...


```
2022-05-06 18:45:33 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry warminator for rinnai
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/httpsession.py", line 178, in send
    response = await self._session.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 539, in _request
    raise ServerTimeoutError(
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host http://169.254.169.254/latest/api/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/rinnai/__init__.py", line 30, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api(
  File "/usr/local/lib/python3.9/site-packages/aiorinnai/api.py", line 114, in async_get_api
    await wh._get_initial_token()
  File "/usr/local/lib/python3.9/site-packages/aiorinnai/api.py", line 78, in _get_initial_token
    await self._store_token(await aws.authenticate_user())
  File "/usr/local/lib/python3.9/site-packages/aiorinnai/aws_srp.py", line 222, in authenticate_user
    async with boto_client as client:
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/session.py", line 22, in __aenter__
    self._client = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/session.py", line 102, in _create_client
    credentials = await self.get_credentials()
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/session.py", line 133, in get_credentials
    self._credentials = await (self._components.get_component(
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/credentials.py", line 814, in load_credentials
    creds = await provider.load()
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/credentials.py", line 486, in load
    metadata = await fetcher.retrieve_iam_role_credentials()
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/utils.py", line 176, in retrieve_iam_role_credentials
    token = await self._fetch_metadata_token()
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/utils.py", line 89, in _fetch_metadata_token
    response = await session.send(request.prepare())
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/httpsession.py", line 209, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"

```

**Comment by explosivo22** [comment]
Yeah it is internal network address.  Oddly enough this is coming from the aiobotocore python module which has had some recent updates.  I am going to dig a little deeper and see what I can get.  I have now been able to replicate the error on my side so hold tight and hopefully we can get this back up and going soon.

**Comment by explosivo22** [comment]
Ok.  I have pushed one more update to the dev version if you wouldn't mind trying it out.  I have successfully cleared the errors on my end, but I would love it if one of you, or both, could confirm the same for me.  Thanks

**Comment by andrewradin** [comment]
how do i get hacs to pull from the dev branch?

**Comment by explosivo22** [comment]
If you click the 3 dots on the Rinnai in HACS, you can choose to do a reinstall and when the version menu pops up you can choose dev from the list.

**Comment by andrewradin** [comment]
aye. i should have noticed that.
came up with no errors this time.  i tested my automations which change temp and activate circulation, all working.

**Comment by andrewradin** [comment]
hmm, outlet and inlet temperature are not updating....

**Comment by explosivo22** [comment]
Great the errors went away.  I saw a log in mine about that to an outdated call that has been removed in code.  Do you have an error in your log as well?

**Comment by andrewradin** [comment]
My logfile is now silent on rinnaicontrolr-ha. 

I tried all my automations. start/stop circulation and set/get heater temp all work. inlet and outlet temp no longer update. I personally don't use these fields so I don't mind.

**Comment by explosivo22** [comment]
Great to hear.  I have some local changes that I will be including in the release.  You might see some renaming of the entities, but the underlying ids shouldn't change so all automations should continue to work.  

Yes the sensors are throttled at 10 minutes due to the fact that to update those sensors takes a more intensive update task on the water heater. I don't want anyone to get theirs locked up doing the tests like mine and have to pull the power each time.

**Comment by psmith3** [comment]
> 

Yes, I did see that address starting with 169. and did not mention it and figured you might if it was an issue. With that said, I had to completely remove my instance from HACS, reinstalled the dev version and am now able to login and see all values! Thanks for the quick investigation and resolve. Look forward to the release.

**Comment by andrewradin** [comment]
re: underlying IDs, please note all stayed the same except binary_sensor.water_heater_recirculation became binary_sensor.water_heater_recirculation_2 on the install of 1.0.45.

**Comment by explosivo22** [comment]
Great to hear. Thanks all for testing and working through this with me. Glad we could get it resolved.
