### ISSUE TITLE
Entity Creation Error

### ISSUE THREAD

**Issue by KoleBarnes** [explosivo22/rinnaicontrolr-ha#52]
Version: 1.3.6 and 1.3.5

```
Logger: homeassistant.components.water_heater
Source: custom_components/rinnai/device.py:134
Integration: Water Heater (documentation, issues)
First occurred: 3:34:49 PM (2 occurrences)
Last logged: 3:34:49 PM

Error adding entities for domain water_heater with platform rinnai
Error while setting up rinnai platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 247, in state_attributes
    is_away = self.is_away_mode_on
  File "/config/custom_components/rinnai/water_heater.py", line 97, in is_away_mode_on
    return self._device.vacation_mode_on
  File "/config/custom_components/rinnai/device.py", line 134, in vacation_mode_on
    return strtobool(str(self._device_information["data"]["getDevice"]["shadow"]["schedule_holiday"]))
  File "/usr/local/lib/python3.10/site-packages/setuptools/_distutils/util.py", line 359, in strtobool
    raise ValueError("invalid truth value {!r}".format(val))
ValueError: invalid truth value 'none'
```

**Comment by explosivo22** [comment]
Please use the beta 1.3.7. I have this scheduled for the next full release, but the beta will fix you up for now.
