### ISSUE TITLE
Only 3 entities showing-up

### ISSUE THREAD

**Issue by sambeetm** [explosivo22/rinnaicontrolr-ha#56]
Since last update, only 3 entities(temp, heating, re-circulation) are showing-up. Rest all shows unavailable. Uninstalled and re-configured the integration without any success.

2023-01-05 21:27:55.962 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up rinnai platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rinnai/sensor.py", line 38, in async_setup_entry
    RinnaiOutletTemperatureSensor(device, config_entry.options),
  File "/config/custom_components/rinnai/sensor.py", line 60, in __init__
    self.options = options
AttributeError: can't set attribute 'options'

**Comment by explosivo22** [comment]
Are you running 2023.1?

**Comment by sambeetm** [comment]
Yes. 2023.1.1Sent from my iPhoneOn Jan 6, 2023, at 5:11 PM, explosivo22 ***@***.***> wrote:﻿
Are you running 2023.1?

**Comment by explosivo22** [comment]
I just upgraded my dev environment and I will test this out.
