### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by vautieri** [explosivo22/rinnaicontrolr-ha#63]
I'm on thr latest release of everything.   I believe everything is working but I do see this error in the log file.

Unexpected error fetching rinnai-191101772WZD5 data: 'maint_interval_enabled'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/rinnai/device.py", line 50, in _async_update_data
    await asyncio.gather(
  File "/config/custom_components/rinnai/device.py", line 219, in _update_device
    if self.options[CONF_MAINT_INTERVAL_ENABLED]:
KeyError: 'maint_interval_enabled'

**Comment by explosivo22** [comment]
I am hoping this issue is resolved for you.  If not, I would say try toggling the maintenance interval under configuration for the integration and see if that resolves this.
