### ISSUE TITLE
Setup failed for custom integration rinnai: Unable to import component: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py)

### ISSUE THREAD

**Issue by RWomer** [explosivo22/rinnaicontrolr-ha#69]
Recently updated home assistant and noticed that the integration would no longer load. The following is the log message.

Logger: homeassistant.setup
Source: custom_components/rinnai/__init__.py:5
Integration: Rinnai Control-R Water Heater ([documentation](https://github.com/explosivo22/rinnaicontrolr-ha/))
First occurred: 3:57:23 PM (1 occurrences)
Last logged: 3:57:23 PM

Setup failed for custom integration rinnai: Unable to import component: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/rinnai/__init__.py", line 5, in <module>
    from aiorinnai import async_get_api
  File "/usr/local/lib/python3.11/site-packages/aiorinnai/__init__.py", line 17, in <module>
    from aiorinnai.api import async_get_api
  File "/usr/local/lib/python3.11/site-packages/aiorinnai/api.py", line 12, in <module>
    from aiorinnai.aws_srp import AWSSRP
  File "/usr/local/lib/python3.11/site-packages/aiorinnai/aws_srp.py", line 19, in <module>
    import aioboto3
  File "/usr/local/lib/python3.11/site-packages/aioboto3/__init__.py", line 5, in <module>
    from aioboto3.session import Session
  File "/usr/local/lib/python3.11/site-packages/aioboto3/session.py", line 9, in <module>
    import aiobotocore.session
  File "/usr/local/lib/python3.11/site-packages/aiobotocore/session.py", line 1, in <module>
    from botocore.session import Session, EVENT_ALIASES, ServiceModel, UnknownServiceError
  File "/usr/local/lib/python3.11/site-packages/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/usr/local/lib/python3.11/site-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/local/lib/python3.11/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/lib/python3.11/site-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/lib/python3.11/site-packages/botocore/awsrequest.py", line 24, in <module>
    import botocore.utils
  File "/usr/local/lib/python3.11/site-packages/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.11/site-packages/botocore/httpsession.py", line 10, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py)

**Comment by explosivo22** [comment]
Interesting. Did this happen after an update or did you just try installing it? I am running on the newest version with no issues right now.

**Comment by RWomer** [comment]
@explosivo22 I did just recently upgrade but I believe it may have already been broken. It used to run and I haven’t changed anything with the Rinnai configuration/device.
