### ISSUE TITLE
Detected blocking call to open inside the event loop

### ISSUE THREAD

**Issue by sambeetm** [explosivo22/rinnaicontrolr-ha#78]
2024-06-08 18:45:19.218 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'rinnai' at custom_components/rinnai/__init__.py, line 49: hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api( (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 172: with open(full_path, 'rb') as fp:), please report it to the author of the 'rinnai' custom integration
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/rinnai/__init__.py", line 49, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api(

**Comment by explosivo22** [comment]
@sambeetm I just wanted to check and see if you are still seeing this. I haven't got it in my instance yet.

**Comment by sambeetm** [comment]
Yes, this issue still present in latest release of HA. Its filling-up the logfile.

2024-06-28 22:17:05.794 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'rinnai' at custom_components/rinnai/__init__.py, line 49: hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api( (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 172: with open(full_path, 'rb') as fp:), please report it to the author of the 'rinnai' custom integration
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/rinnai/__init__.py", line 49, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api(

**Comment by explosivo22** [comment]
I may have a solution to this. I am going to run it a little longer in my instance and then if all goes well I will publish a release.

**Comment by scottrfrancis** [comment]
if it's any help to you, I'm happy to help test/debug

**Comment by explosivo22** [comment]
I dropped the ball on this one. I have tested and confirmed the issue is fixed, but I forgot I didn't publish a new release yet. I will get this out today.
