### ISSUE TITLE
Error occurring after HA restart: ImportError: cannot import name 'resolve_checksum_context' from 'botocore.client'

### ISSUE THREAD

**Issue by billpribyl** [explosivo22/rinnaicontrolr-ha#81]
Restarted HA and got this the error at the bottom. 

After that, rebooted the HA host and got:  "2024-07-25 14:31:01.753 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data/cognito-idp',) inside the event loop by custom integration 'rinnai' at custom_components/rinnai/__init__.py, line 49: hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api( (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 363: for dirname in os.listdir(possible_path):), please report it to the author of the 'rinnai' custom integration"

But it seems to be working now.

Here's the error stack that I saw:

Logger: homeassistant.setup
Source: setup.py:322
First occurred: 14:18:18 (1 occurrences)
Last logged: 14:18:18

Setup failed for custom integration 'rinnai': Unable to import component: cannot import name 'resolve_checksum_context' from 'botocore.client' (/usr/local/lib/python3.12/site-packages/botocore/client.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 990, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1050, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/rinnai/__init__.py", line 5, in <module>
    from aiorinnai import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/__init__.py", line 17, in <module>
    from aiorinnai.api import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/api.py", line 12, in <module>
    from aiorinnai.aws_srp import AWSSRP
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/aws_srp.py", line 19, in <module>
    import aioboto3
  File "/usr/local/lib/python3.12/site-packages/aioboto3/__init__.py", line 5, in <module>
    from aioboto3.session import Session
  File "/usr/local/lib/python3.12/site-packages/aioboto3/session.py", line 9, in <module>
    import aiobotocore.session
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/session.py", line 12, in <module>
    from .client import AioBaseClient, AioClientCreator
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/client.py", line 2, in <module>
    from botocore.client import (
ImportError: cannot import name 'resolve_checksum_context' from 'botocore.client' (/usr/local/lib/python3.12/site-packages/botocore/client.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1010, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1002, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1050, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/rinnai/__init__.py", line 5, in <module>
    from aiorinnai import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/__init__.py", line 17, in <module>
    from aiorinnai.api import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/api.py", line 12, in <module>
    from aiorinnai.aws_srp import AWSSRP
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/aws_srp.py", line 19, in <module>
    import aioboto3
  File "/usr/local/lib/python3.12/site-packages/aioboto3/__init__.py", line 5, in <module>
    from aioboto3.session import Session
  File "/usr/local/lib/python3.12/site-packages/aioboto3/session.py", line 9, in <module>
    import aiobotocore.session
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/session.py", line 12, in <module>
    from .client import AioBaseClient, AioClientCreator
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/client.py", line 2, in <module>
    from botocore.client import (
ImportError: cannot import name 'resolve_checksum_context' from 'botocore.client' (/usr/local/lib/python3.12/site-packages/botocore/client.py)

**Comment by srpomeroy** [comment]
I am getting the same error after updating HA to` 2024.7.3` and rinnai to `v1.4.3`.

```
Logger: homeassistant.setup
Source: setup.py:322
First occurred: 9:22:58 PM (1 occurrences)
Last logged: 9:22:58 PM

Setup failed for custom integration 'rinnai': Unable to import component: cannot import name 'resolve_checksum_context' from 'botocore.client' (/usr/local/lib/python3.12/site-packages/botocore/client.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/rinnai/__init__.py", line 5, in <module>
    from aiorinnai import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/__init__.py", line 17, in <module>
    from aiorinnai.api import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/api.py", line 12, in <module>
    from aiorinnai.aws_srp import AWSSRP
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/aws_srp.py", line 19, in <module>
    import aioboto3
  File "/usr/local/lib/python3.12/site-packages/aioboto3/__init__.py", line 5, in <module>
    from aioboto3.session import Session
  File "/usr/local/lib/python3.12/site-packages/aioboto3/session.py", line 9, in <module>
    import aiobotocore.session
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/session.py", line 12, in <module>
    from .client import AioBaseClient, AioClientCreator
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/client.py", line 2, in <module>
    from botocore.client import (
ImportError: cannot import name 'resolve_checksum_context' from 'botocore.client' (/usr/local/lib/python3.12/site-packages/botocore/client.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/rinnai/__init__.py", line 5, in <module>
    from aiorinnai import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/__init__.py", line 17, in <module>
    from aiorinnai.api import async_get_api
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/api.py", line 12, in <module>
    from aiorinnai.aws_srp import AWSSRP
  File "/usr/local/lib/python3.12/site-packages/aiorinnai/aws_srp.py", line 19, in <module>
    import aioboto3
  File "/usr/local/lib/python3.12/site-packages/aioboto3/__init__.py", line 5, in <module>
    from aioboto3.session import Session
  File "/usr/local/lib/python3.12/site-packages/aioboto3/session.py", line 9, in <module>
    import aiobotocore.session
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/session.py", line 12, in <module>
    from .client import AioBaseClient, AioClientCreator
  File "/usr/local/lib/python3.12/site-packages/aiobotocore/client.py", line 2, in <module>
    from botocore.client import (
ImportError: cannot import name 'resolve_checksum_context' from 'botocore.client' (/usr/local/lib/python3.12/site-packages/botocore/client.py)
```

**Comment by andrewradin** [comment]
I have the same issue. Happy to help you debug lemme know.

**Comment by genehand** [comment]
I had some similar issues with 2024.8.1.  I bumped aioboto3 to the latest in a fork at https://github.com/genehand/aiorinnai.  You can try it out by changing the rinnai manifest.json:

```json
"requirements": [ "aiorinnai @ git+https://github.com/genehand/aiorinnai.git@main" ],
```

All good here now, I can get some PR's in later this week.

**Comment by explosivo22** [comment]
Apologies for the delay. I am working on deploying out the fix

**Comment by explosivo22** [comment]
I am curious. Would you all like a full local version? I have been working on one, but I was made aware that the RWM200 doesn't seem to have the open ports so this wouldn't work for anyone with that controller.

**Comment by explosivo22** [comment]
Yep. I have it running in my test environment controlling everything locally and pulling information. I just need to finish the config flow for setting up via IP. I hope to have that done soon and tested. I will be more than happy to get other testers as well.

**Comment by andrewradin** [comment]
I’m happy to do some testing if it would be helpful.
While you are working on this please consider – I have two control-Rs. If you are doing to do some fancy network probe, please keep this in mind.
Also, my home assistant has several network interfaces as I have isolated 3rd party devices on a vlan. Be sure to probe all networks.

**Comment by wrmacj** [comment]
I also would like to test your HASS integrated Local version. It would be helpful if it includes wifi strength.   That is often why people have trouble running the integration. 

I have also had a stable local version running off via powershell and outputting results to a text file. 
with a good wifi signal it was perfectly stable polling for results every 15 seconds making better graphs.

**Comment by explosivo22** [comment]
> I also would like to test your HASS integrated Local version. It would be helpful if it includes wifi strength. That is often why people have trouble running the integration.
> 
> I have also had a stable local version running off via powershell and outputting results to a text file. with a good wifi signal it was perfectly stable polling for results every 15 seconds making better graphs.

@wrmacj Was this just the update interval you were using or were you also running the maintenance cycle?

**Comment by explosivo22** [comment]
Please try release 1.5.2

**Comment by andrewradin** [comment]
No workie. two error logs, below.

==============================================================

Logger: homeassistant.loader
Source: loader.py:1075
First occurred: 4:04:45 PM (2 occurrences)
Last logged: 4:04:45 PM

Unexpected exception importing component custom_components.rinnai
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/rinnai/__init__.py", line 176
    >>>>>>> 6a60ac3ef2862a01b180479f5b5a2e441f6a6f88:custom_components/rinnai/__init__.py
            ^
SyntaxError: invalid decimal literal


==============================================================


Logger: homeassistant.setup
Source: setup.py:340
First occurred: 4:04:45 PM (1 occurrences)
Last logged: 4:04:45 PM

Setup failed for custom integration 'rinnai': Unable to import component: Exception importing custom_components.rinnai
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/rinnai/__init__.py", line 176
    >>>>>>> 6a60ac3ef2862a01b180479f5b5a2e441f6a6f88:custom_components/rinnai/__init__.py
            ^
SyntaxError: invalid decimal literal

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1086, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.rinnai

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/rinnai/__init__.py", line 176
    >>>>>>> 6a60ac3ef2862a01b180479f5b5a2e441f6a6f88:custom_components/rinnai/__init__.py
            ^
SyntaxError: invalid decimal literal

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 340, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1086, in _get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.rinnai

**Comment by andrewradin** [comment]
also, can't revert to last working version 1.4.3, can you resolve this one first please?

--

Downloading explosivo22/rinnaicontrolr-ha with version 1.4.3 failed with (No manifest.json file found 'custom_components/rinnai/manifest.json')

**Comment by explosivo22** [comment]
could you try 1.5.4

**Comment by andrewradin** [comment]
nope.

--

Logger: homeassistant.config_entries
Source: config_entries.py:637
First occurred: 4:47:05 PM (1 occurrences)
Last logged: 4:47:05 PM

Error setting up entry warminator for rinnai
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 637, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rinnai/__init__.py", line 38, in async_setup_entry
    await client.async_renew_access_token(entry.data[CONF_EMAIL], entry.data[CONF_ACCESS_TOKEN], entry.data[CONF_REFRESH_TOKEN])
                                                                  ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'conf_access_token'

**Comment by andrewradin** [comment]
> also, can't revert to last working version 1.4.3, can you resolve this one first please?
> 
> --
> 
> Downloading explosivo22/rinnaicontrolr-ha with version 1.4.3 failed with (No manifest.json file found 'custom_components/rinnai/manifest.json')

this is now fixed, thank you.

**Comment by explosivo22** [comment]
> nope.
> 
> --
> 
> Logger: homeassistant.config_entries Source: config_entries.py:637 First occurred: 4:47:05 PM (1 occurrences) Last logged: 4:47:05 PM
> 
> Error setting up entry warminator for rinnai Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 637, in __async_setup_with_context result = await component.async_setup_entry(hass, self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/rinnai/**init**.py", line 38, in async_setup_entry await client.async_renew_access_token(entry.data[CONF_EMAIL], entry.data[CONF_ACCESS_TOKEN], entry.data[CONF_REFRESH_TOKEN]) ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^ KeyError: 'conf_access_token'

this is related to the change that was necessary for the dependency.  I believe a remove and config again would fix this, but I am investigating the migration for the config flow

**Comment by andrewradin** [comment]
remove of just the integration or the repository from hacs?

when I upgraded from 1.4.3 to 1.5.2 I couldn't remove the integration and things got wonky (because I could remove the repository). I was only able to move forward by restoring my system from a backup.

1.4.3. to 1.5.3 and back to 1.4.3 worked without having to restore from backup.

**Comment by explosivo22** [comment]
@andrewradin go ahead and give 1.5.6 a try if you haven't already.  I have had reports of success

**Comment by andrewradin** [comment]
> [@andrewradin](https://github.com/andrewradin) go ahead and give 1.5.6 a try if you haven't already. I have had reports of success

1.5.6 does indeed work, thank you.

In the future please note that if someone gets in the state where they end up removing the repository but not the integration (because the integration can't be removed due to throwing an exception) it turns out a 'ha supervisor repair' does exactly what you think it does and repairs it.

**Comment by explosivo22** [comment]
> > [@andrewradin](https://github.com/andrewradin) go ahead and give 1.5.6 a try if you haven't already. I have had reports of success
> 
> 1.5.6 does indeed work, thank you.
> 
> In the future please note that if someone gets in the state where they end up removing the repository but not the integration (because the integration can't be removed due to throwing an exception) it turns out a 'ha supervisor repair' does exactly what you think it does and repairs it.

Great to hear it works. Thanks for the additional info. I think that is something good to know.
