### ISSUE TITLE
Rinnai Throwing Errors since recent Home Assistant Update - and results in Home Assistant UI Becoming non-responsive

### ISSUE THREAD

**Issue by peterbrown05** [explosivo22/rinnaicontrolr-ha#86]
Hey there
Rinnai integration has been working fine. Recently, updated the home assistant core/version and I think it was after this that I started seeing the following problem.

Specifically things seem fine, then the Home Assistant UI becomes non responsive and eventually timesout and then needs to be restarted. Looking in logs, it is full of the errors like the 3 below;

Now running:

 Version: 2024.10.4
 OSVersion: 13.2

I tried a few power cycles, but the same problem repeated.

Since disabling Rinnai, the Home Assistant and its UI access has been stable.
here's the example logs Im seeing.

```
2024-10-26 20:20:56.670 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data',) inside the event loop by custom integration 'rinnai' at custom_components/rinnai/__init__.py, line 49: hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api( (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 306: for d in os.listdir(possible_path)), please report it to the author of the 'rinnai' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/rinnai/__init__.py", line 49, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api(

2024-10-26 20:20:56.917 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data/devops-guru',) inside the event loop by custom integration 'rinnai' at custom_components/rinnai/__init__.py, line 49: hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api( (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 311: api_versions = os.listdir(full_dirname)), please report it to the author of the 'rinnai' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/rinnai/__init__.py", line 49, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api(

2024-10-26 20:21:01.839 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to listdir with args ('/usr/local/lib/python3.12/site-packages/botocore/data/cognito-idp',) inside the event loop by custom integration 'rinnai' at custom_components/rinnai/__init__.py, line 49: hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api( (offender: /usr/local/lib/python3.12/site-packages/botocore/loaders.py, line 363: for dirname in os.listdir(possible_path):), please report it to the author of the 'rinnai' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/rinnai/__init__.py", line 49, in async_setup_entry
    hass.data[DOMAIN][entry.entry_id][CLIENT] = client = await async_get_api(

```

**Comment by explosivo22** [comment]
I have been tracking all of these and I am currently working on a couple things. The backend library is one which is requiring a full rewrite. I am also investigating just going down to a full local integration, but this will eliminate the newest control module as we haven't found any open ports yet. #81

**Comment by explosivo22** [comment]
I am going to be looking at doing an API rewrite in hopes to remove all these errors. If you have the RWM103, I just did a pre-release for a full local integration. If you are on the newer RWM200, you will have to wait until I can finish up the rewrite.

**Comment by explosivo22** [comment]
Please try release 1.5.2

**Comment by peterbrown05** [comment]
hey there - ive been running 2.1.5 for version around 1.5 weeks now; and just to say it looks really good. no longer seeing the above issues, and Im able to control recirculation etc from HA. Many thanks for fixing this.
